[package]
name = "rustsbi-qemu"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = { git = "https://github.com/rustsbi/rustsbi", rev = "674c8ee9" }
buddy_system_allocator = "0.8"
lazy_static = { version = "1", features = ["spin_no_std"] }
spin = "0.9"
riscv = { git = "https://github.com/rust-embedded/riscv", rev = "7e9d2e5b", features = ["inline-asm"] }
device_tree = { git = "https://github.com/rcore-os/device_tree-rs/" }
embedded-hal = "0.2.6"
nb = "1"
bitflags = "1"
bit_field = "0.10"
hashbrown = "0.11"
