[package]
name = "xtask"
version = "0.1.0"
authors = ["Luo Jia <me@luojia.cc>"]
description = "interactive cargo runner"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
ctrlc = "3.2"
