[package]
name = "hsm-cell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-spec = "0.0.4"

[lib]
name = "hsm_cell"
test = false
bench = false
